### ISSUE TITLE
Question about "Pull requests"

### ISSUE THREAD

**Issue by Color-maN** [Freddywhest/WuykzEas0LDTwIhjYNYES5v7yZcQcK0B#2]
I do not know how to use "Pull requests". I hope I did everything right. I have updated the latest MemeFi codes. Please tell me how to do this. I don't understand.

**Comment by Freddywhest** [comment]
git pull -> to get up to date repo (if you have already fork it)

If not follow below guide:

### Step 1: Fork the Repository (If You Haven't Already)
1. Go to the original repository on GitHub.
2. Click on the **Fork** button (usually at the top right).
3. This creates a copy of the repository in your GitHub account.

### Step 2: Clone the Forked Repository Locally
If you haven’t cloned your forked repository, do this from your GitHub account:
1. Click on **Code** in your forked repo and copy the URL.
2. Run the following command in your terminal to clone it:
   ```bash
   git clone <your-fork-url>
   ```

### Step 3: Create a New Branch
1. Navigate into the project folder:
   ```bash
   cd <your-repo-name>
   ```
2. Create and switch to a new branch for your changes:
   ```bash
   git checkout -b update-memefi-codes
   ```

### Step 4: Make Your Changes
1. Edit the code and save your changes.

### Step 5: Commit and Push Your Changes
1. Stage your changes:
   ```bash
   git add .
   ```
2. Commit your changes with a message:
   ```bash
   git commit -m "Updated MemeFi codes"
   ```
3. Push the branch to your forked repository:
   ```bash
   git push origin update-memefi-codes
   ```

### Step 6: Create a Pull Request
1. Go to the original repository on GitHub.
2. You should see an option to create a pull request for your branch.
3. Click **Compare & pull request**.
4. Add a title and description, then click **Create pull request**.

Once your pull request is reviewed, it can be merged into the main project. Let me know if you need help with any specific step!

**Comment by Color-maN** [comment]
Thank you very much! Now I know
